package com.com.redhat.demo.dmn.car_insurance_quote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Proposal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Driver")
	private com.com.redhat.demo.dmn.car_insurance_quote.Driver driver;
	@org.kie.api.definition.type.Label(value = "Vehicle")
	private com.com.redhat.demo.dmn.car_insurance_quote.Car vehicle;
	@org.kie.api.definition.type.Label(value = "Quote")
	private java.math.BigDecimal quote;
	@org.kie.api.definition.type.Label(value = "Auto Approve")
	private java.lang.Boolean autoApprove;

	public Proposal() {
	}

	public com.com.redhat.demo.dmn.car_insurance_quote.Driver getDriver() {
		return this.driver;
	}

	public void setDriver(
			com.com.redhat.demo.dmn.car_insurance_quote.Driver driver) {
		this.driver = driver;
	}

	public com.com.redhat.demo.dmn.car_insurance_quote.Car getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(
			com.com.redhat.demo.dmn.car_insurance_quote.Car vehicle) {
		this.vehicle = vehicle;
	}

	public java.math.BigDecimal getQuote() {
		return this.quote;
	}

	public void setQuote(java.math.BigDecimal quote) {
		this.quote = quote;
	}

	public java.lang.Boolean getAutoApprove() {
		return this.autoApprove;
	}

	public void setAutoApprove(java.lang.Boolean autoApprove) {
		this.autoApprove = autoApprove;
	}

	public Proposal(com.com.redhat.demo.dmn.car_insurance_quote.Driver driver,
			com.com.redhat.demo.dmn.car_insurance_quote.Car vehicle,
			java.math.BigDecimal quote, java.lang.Boolean autoApprove) {
		this.driver = driver;
		this.vehicle = vehicle;
		this.quote = quote;
		this.autoApprove = autoApprove;
	}

}